language: node_js
node_js:
  - "10.0"
  - "11.0"
sudo: false
script:
  # Run test script
  - npm run test-ci
  # Run linting
  - npm run lint
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls@2.13.3
    coveralls < ./coverage/lcov.info